
export SHELL := /bin/bash

all:
	pdflatex finalspec.tex
	pdflatex finalspec.tex
	pdflatex finalspec.tex

clean:
	$(RM) *.dvi *.aux *.log *.bbl *.blg *.toc *.out *.fls *.haux *.fdb_latexmk 

distclean: clean



