
export SHELL := /bin/bash

all:
	pdflatex spec.tex
	pdflatex spec.tex
	pdflatex spec.tex

clean:
	$(RM) *.dvi *.aux *.log *.bbl *.blg *.toc *.out *.fls *.haux *.fdb_latexmk 

distclean: clean
	$(RM) *.dvi *.aux *.log *.bbl *.blg *.toc *.out *.fls *.haux *.fdb_latexmk 



